[package]
name = "tol2"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.1.1"
clap = { version = "4.5.53", features = ["derive"] }
predicates = "3.1.3"

[[tests]]
name = "integration_tests"
path = "tests"
